containers:
  core:
    image: gentoo/stage3:systemd
    entrypoint: ["/lib/systemd/systemd"]
    stopSignal: RTMIN+3
    tty: true
    disableInit: true
    workingDirectory: /
    mounts:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /run/udev:/run/udev
      - /mnt:/mnt
      - /mnt/persist/core-docker:/var/lib/docker
      - /mnt/persist/skiff/core/repos/binpkgs:/var/cache/binpkgs
      - /mnt/persist/skiff/core/repos/distfiles:/var/cache/distfiles
      - /mnt/persist/skiff/core/repos/gentoo:/var/db/repos/gentoo
      - /mnt/persist/skiff/core/repos/linux:/usr/src
      - /mnt/persist/skiff/core/repos/log:/var/log
      - /mnt/persist/skiff/core/repos/portage-build:/var/tmp/portage
    privileged: true
    startAfterCreate: true
    restartPolicy: "always"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    capAdd:
      - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
      - seccomp=unconfined
users:
  core:
    container: core
    containerUser: core
    createContainerUser: true
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  gentoo/stage3:systemd:
    pull:
      # images are provided for arm64, arm, amd64
      # also an option: policy: ifbuildfails
      policy: ifbuildfails
    build:
      source: /opt/skiff/coreenv/skiff-core-gentoo
